#!/bin/sh

global.hostname=pcm049
eth0.serverip=
user=

# use 'dhcp' to do dhcp in barebox and in kernel
# use 'none' if you want to skip kernel ip autoconfiguration
ip=dhcp

# or set your networking parameters here
#eth0.ipaddr=a.b.c.d
#eth0.netmask=a.b.c.d
#eth0.gateway=a.b.c.d
#eth0.serverip=a.b.c.d

# can be either 'nfs', 'tftp', 'nor' or 'nand'
kernel_loc=nand
# can be either 'net', 'nor', 'nand' or 'initrd'
rootfs_loc=nand

# can be either 'jffs2' or 'ubifs'
rootfs_type=ubifs
rootfsimage=root-${global.hostname}.$rootfs_type

#kernelimage=zImage-${global.hostname}
kernelimage=uImage-${global.hostname}
#kernelimage=Image-${global.hostname}
#kernelimage=Image-${global.hostname}.lzo

if [ -n $user ]; then
	kernelimage="$user"-"$kernelimage"
	nfsroot="$eth0.serverip:/home/$user/nfsroot/${global.hostname}"
	rootfsimage="$user"-"$rootfsimage"
else
	nfsroot="$eth0.serverip:/path/to/nfs/root"
fi

autoboot_timeout=3

# Android kernel requirements
bootargs="$bootargs init=/init vram=64M omapfb.vram=0:32M"

nand_parts="128k(xload)ro,512k(barebox),128k(bareboxenv),6M(kernel),4M(splash),-(root)"
nand_device="omap2-nand.0"
rootfs_mtdblock_nand=5

#Display
display=nhd50800480tf-atxl
#display=nhd43480272ef-atxl

if [ -n ${global.displayargs} ]; then
	bootargs="$bootargs ${global.displayargs}"
fi

# set a fancy prompt (if support is compiled in)
PS1="\e[1;32mbarebox@\e[1;31m\h:\w\e[0m "

